### ISSUE TITLE
Can't generate bootstrap-friendly views

### ISSUE THREAD

**Issue by u2** [dhampik/rails-admin-scaffold#12]
`gem 'rails', '4.1.5'`
`rails g admin:scaffold_controller Six state:boolean --parent_controller=admin --bootstrap`
Can't generate bootstrap-friendly views.The views is the same as no-`--bootstrap`.

**Comment by joshuapaling** [comment]
What version of rails-admin-scaffold are you using?

**Comment by u2** [comment]
0.0.5
I have find that this is new feature of 0.1.0, right?Sorry about that.Never mind ;)

**Comment by joshuapaling** [comment]
Yep, it's available in 0.1.0. Let me know if you still have issues after upgrading.

**Comment by u2** [comment]
It's workable now!
Thanks.
