### ISSUE TITLE
Overriding templates

### ISSUE THREAD

**Issue by alepore** [dhampik/rails-admin-scaffold#5]
Hi,
looks like i'm not able to use custom templates, i've copied them as `lib/templates/admin/scaffold_controller/views/erb/*.html.erb.erb`

I'm on rails 4.1.4, any idea?

**Comment by alepore** [comment]
nevermind, did a bundle/reboot and works now

**Comment by johanbaaij** [comment]
hi. would `lib/templates/admin/scaffold_controller/controllers/railties/controller.rb.erb` be the correct path to override the controller template?

**Comment by maslenkov** [comment]
@johanbaaij Yes, it looks correct. Any problems?

**Comment by johanbaaij** [comment]
no, no problems. it turned out i had to override the jbuilder one instead. all works good now, thanks.
